### ISSUE TITLE
Include workspace metadata in medium privacy outputs

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-runner#158]
When writing outputs of a job, we should include a `.opensafely.json` file in the medium privacy/level output directy, sth like so:

```json
    {
        "repo": "https://github.com/opensafley/study",
        "workspace": "workspace"
    }
```

This metadata would be synced to the level 4 server, where it can be used by osrelease as the origin for publishing to github. This means the user a) have to remember the repo b) can't get confused by repo vs workspaces and b) prevents accidentally publishing to the wrong repo.

We may want to stick more things in here in future, perhaps.

**Comment by evansd** [comment]
Closed by #161
