### ISSUE TITLE
Improve performance of copying large numbers of files in/out of Docker volumes

### ISSUE THREAD

**Issue by evansd** [opensafely-core/job-runner#169]
The issue is that each file is copied by a separate shell out to `docker cp` which, for large numbers of small files, creates a lot of overhead.

This is mainly a problem when generating measures (which can create lots of files) and mainly a problem when developing locally where the slowness has a big impact on the feedback loop and hence on productivity.

It's therefore worthwhile to make the code slightly more complex in order to batch up the copies. For instance, if we can determine that we're copying every file in a directory (as we often are) then we can just copy the directory.

**Comment by bloodearnest** [comment]
One way to do this much betterer is to use a single rsync command, rather than `docker cp` each file.

`rsync -e 'docker exec -i'  $file1 $file2 ... $container:/workspace/` seems to work.

This would also give us the ability to resume an interupted prepare stage too, rsync would re-run can carry on as needed. This means we could restart job-runner whenever, which is important if we want automated deploys.

It would need rsync in the image, however. We could add it to base-action though. https://github.com/opensafely-core/base-docker/blob/master/Dockerfile

It also requires rsync binary in git-bash, but this is potentially available: https://prasaz.medium.com/add-rsync-to-windows-git-bash-f42736bae1b3.  And also not an issue once we move to ubuntu VM.

**Comment by evansd** [comment]
Just to add, I _think_ we could include rsync in our "container management" image and avoid having it in the base image -- not that it's necessarily a problem to have it there.

**Comment by bloodearnest** [comment]
Hmm, using docker exec does mean it needs to be in the management image, actually, yeah.

Which plays nicely with the recent change to have the management image running all the time, actually.

However, I do tangentially think we don't need busybox as the management image, and could instead use `base-action`, which would actually save us disk space as we wouldn't need busybox anymore

**Comment by bloodearnest** [comment]
I did a quick benchmark on `docker cp` on each file in a directory, and `rsync`ing an entire directory, and sadly, `rsync` is about 2x slower that `docker cp` on linux with docker on zfs

rsync is resumable, which makes it potentially interesting in producion, but not in local usage.

It's probably worth trying this on windows too, as the performance tradeoff might be different there.

```
$ tree testdir
testdir
├── a
│   └── filea.csv
├── b
│   └── fileb.csv
├── c
│   └── filec.csv
├── d
│   └── filed.csv
├── e
│   └── filee.csv
├── f
│   └── filef.csv
├── g
│   └── fileg.csv
├── h
│   └── fileh.csv
└── i
    └── filei.csv

9 directories, 9 files
$ du -sh testdir
4.4G	testdir
$ cat test_cp.py 
from pathlib import Path
import subprocess

testdir = Path("testdir")

for f in testdir.glob("**/*"):
    if not f.is_file():
        continue
    subprocess.run(["docker", "cp", f, f"test-cp:/vol/{f.name}"])

$ time python3 test_cp.py 

real	0m4.660s
user	0m2.303s
sys	0m4.524s

$ time rsync -r -e "docker exec -i" testdir/ test-cp:/vol/

real	0m8.774s
user	0m6.449s
sys	0m3.993s
```

**Comment by sebbacon** [comment]
Do I remember right that we have now identified a different thing that was faster? Maybe it was a weird dream.

**Comment by evansd** [comment]
I think this can be split into two separate issues. One is make things faster in production, where we're now always on Linux. The other is to make this faster for local development, where we still need to support Windows.

In production the approach is fairly simple: instead of using docker volumes we use temporary directories which we can then bind mount in. (Which is exactly what v0.1 of job-runner did, except this had horrible performance on Windows.) This makes copying files in a local filesystem operation with no docker involvement. Copies out can actually then become _moves_ out, which will be faster still.

Locally, we'll still need to use docker volumes. But the performance issues are different here as it's not really the volume of data that's the issue, but the number of files. I think part of the problem would be alleviated by a [better measures implementation](https://github.com/opensafely-core/databuilder/issues/42#issuecomment-1085873926) that didn't involve copying out and then back in again lots of small files. But maybe some of the other tricks discussed above (rsync, better batching behaviour) would still be useful here.

**Comment by bloodearnest** [comment]
SNAP!

**Comment by bloodearnest** [comment]
The hardlinking might not be practical, we may need to copy instead, but it would be faster than current docker cp for sure.

**Comment by evansd** [comment]
> hardlink input files into temporary directory and make read-only to docker

Ooh, I'd forgotten about that bit. Yes, that would be great but might not be practical as you say and just using local operations would be such a win anyway.

**Comment by sebbacon** [comment]
Closed in favour of two new issues. Thanks!
