### ISSUE TITLE
Indicate likely out-of-memory errors to user

### ISSUE THREAD

**Issue by evansd** [opensafely-core/job-runner#208]
When a Docker container exits with status 137 (process received SIGKILL) this is usually because it's been nuked by the OOM killer. When this happens we should include something helpful in the log "trailer" which lets users know this, otherwise it's quite confusing.

See e.g. https://github.com/opensafely/documentation/discussions/245

**Comment by evansd** [comment]
If this happens locally, we should include a link to instructions on how to increase Docker's memory allocation.

If this happens during a cohortextractor dummy data run we should include a note that it might be that the population size is too large.

**Comment by venexia** [comment]
I would like to second this request.
