### ISSUE TITLE
Change default branch from master to main

### ISSUE THREAD

**Issue by benbc** [opensafely-core/job-runner#222]
For more information about why we're changing, see: opensafely/research-template#32.

**Comment by evansd** [comment]
@bloodearnest I can do the necessary fiddling for the TPP and EMIS deployments. Is there anything special we need to do for NHSD?

**Comment by bloodearnest** [comment]
urg, this is a bit ugly

We'll need to automate the migration from master->main in https://github.com/opensafely-core/backend-server

**Comment by bloodearnest** [comment]
another argument for switching to docker deploy of job-runner

**Comment by evansd** [comment]
Ah, right yes. Well maybe we just punt this for now then and tackle it when we're redoing the deployment strategy.

**Comment by madwort** [comment]
can we just do this, already? https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1678976998559979

**Comment by madwort** [comment]
we think we can just do it & fix things that arise. possible places of breakage:

* backend-server tests
* redirecting through the github proxy (will the redirect calls be blocked?)
* nb. we do still use EMIS, so we do need to update that too - only a couple of people have access to that

**Comment by madwort** [comment]
- [x] branch renamed on github
- [ ] update environments
  - [x] TPP
  - [ ] EMIS
  - [ ] ...?
- [ ] fix any other breakage

**Comment by madwort** [comment]
it appears that nothing has gone wrong so far...
