### ISSUE TITLE
Review and prioritise output file options listed in this issue

### ISSUE THREAD

**Issue by evansd** [opensafely-core/job-runner#261]
This ticket collects together various issues people have had with specifying with the `outputs:` section of an action specified in a `project.yaml` file.

I think we're due a wider rethink of the way of we specify inputs and outputs and so it's useful to collect these in one place.

### 1. Input files get accidentally captured as output files
Issue: https://github.com/opensafely-core/job-runner/issues/180

A fairly rare one I think, but very confusing when it happens

### 2. The requirement for global uniqueness of output patterns leads to silly workarounds

This means writing patterns like `output/inpu*.csv` and `output/inp*t.csv` to avoid writing exactly the same name twice.
I remember this occurring a few times but I don't have links to any specific examples (maybe @alexwalkercebm does?). I'd be very keen to see these because I feel like this shouldn't be necessary but obviously it was. We've discussed dropping the uniqueness requirement which would make this go away but I actually think there might be good reason to keep it so I'd be keen to get to the bottom of the problem here.

### 3. You can't do in-place updates of files which is the standard workflow for jupyter notebooks

Issue: https://github.com/opensafely-core/job-runner/issues/155

I want to say that we just shouldn't support this as clean separation of code and data is a core OpenSAFELY principle. But obviously we need _some_ workflow to support jupyter notebooks which is well documented and not too onerous for researchers. This probably needs input from someone more practised with jupyter than I am.

### 4. Some outputs may not always be generated, depending on the data
Issue: https://github.com/opensafely/documentation/discussions/378

@wjchulme  has suggested a reasonable workaround here: generating a text file matching the output pattern which explains why no images were produced). However this specific trick won't work if we implement the suggestion [here](https://github.com/opensafely-core/job-runner/issues/159) to disallow open-ended wildcards and require all glob patterns to specific an extension. Generating an appropriate placeholder image instead of a text file might be a lot more work. But maybe it would be possible to make the image by hand and commit it to the repo and the code could then just copy it in place if needed.

I think we should consider explicitly supporting optional outputs, although if we can come up with a not too onerous standard workaround then there are advantages to keeping the output specification simple, and this issue hasn't come up too many times so far.

### 5. There's no way to specify that you just need one file from a previous action and so the job-runner copies all its outputs which is slow and wastes disk space in production

I don't have an associated issue for this, but I know it's been a problem in practice.

**Comment by evansd** [comment]
An option that @bloodearnest and I have previously discussed but not written down is to do away with the requirement for an explicit `needs:` list to specify dependencies and instead have an `inputs:` list, with the same format as the `outputs:` list. The job-runner could then infer which actions needed to be run based on which files were required. 

This would allow us to solve 5 above, and the symmetry of `inputs` and `outputs` might be conceptually simpler for new users.

It would mean we bake in the requirement for unique output patterns though (if two actions have identical patterns the job-runner can't know which to run to generate the required outputs), which means coming up with good answers for 2 and 3.

**Comment by bloodearnest** [comment]
This `inputs:` option might be worth doing as part of the graphnet voyage work. We will be moving to copying files around a network/cloud, so minimising that would be good.

**Comment by sebbacon** [comment]
To summarise the current set of proposals (and closely-related):

* [input files get captured as outputs](https://github.com/opensafely-core/job-runner/issues/180)
* [local run mode should check for patient level data mislabelled as _moderately_ sensitive](https://github.com/opensafely-core/job-runner/issues/315)
* [replace `needs` with `inputs`](https://github.com/opensafely-core/job-runner/issues/319)
* [privacy levels via reserved directory names](https://github.com/opensafely-core/job-runner/issues/320)

**Comment by iaindillingham** [comment]
There's an example of the second issue (working around the global uniqueness check) in the [pincer-measures study](https://github.com/opensafely/pincer-measures/blob/main/project.yaml).

This technique is used to split weekly/monthly extracts into several actions, such that if one fails, they don't all fail. @HelenCEBM discusses it  [here](https://github.com/opensafely/documentation/issues/594) and @LFISHER7 [here](https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1649415639602019?thread_ts=1649415639.602019&cid=C01D7H9LYKB).

**Comment by iaindillingham** [comment]
I've attempted to place the issues in priority order, with dependant issues shown as sub-tasks of the dependee task. My rationale follows.

opensafely-core/job-runner#315 is self-contained, well specified, and an important security precaution. The basic check could be implemented to address the issue; further checks would require more design work, but this could happen in further issues.

opensafely-core/job-runner#319 is well specified, but needs to be reconciled with opensafely-core/job-runner#155 and opensafely-core/job-runner#180. It may not be possible to implement both opensafely-core/job-runner#319 and opensafely-core/job-runner#155. It isn't possible to implement both opensafely-core/job-runner#319 and opensafely-core/job-runner#180. However, both dependant issues have been reported by users and the workaround for opensafely-core/job-runner#180 has been regularly spotted in the wild (it's in two studies; it's being discussed for inclusion in the documentation; it's being discussed on Slack).

I would suggest implementing opensafely-core/job-runner#319 and not implementing opensafely-core/job-runner#180. This is going to cause some users some pain, so it would be useful to know whether Data Builder can make weekly/monthly extracts over long time periods more reliable.

As @evansd, I would suggest doing more design work on opensafely-core/job-runner#155.

opensafely-core/job-runner#320 is mostly self-contained, but it makes most sense to address it after opensafely-core/job-runner#315 and opensafely-core/job-runner#319, for the reasons given in the issue.

**Comment by evansd** [comment]
> I would suggest implementing https://github.com/opensafely-core/job-runner/issues/319 and not implementing https://github.com/opensafely-core/job-runner/issues/180. This is going to cause some users some pain, so it would be useful to know whether Data Builder can make weekly/monthly extracts over long time periods more reliable.

Thanks @iaindillingham. I agree with your suggested approach. Here are a few possibly helpful remarks.

1. I don't think enforcing non-overlapping patterns completely precludes the kind of "split extracts into multiple actions" workaround it's currently being used for.

   The outputs from the various `generate_study_population_N` actions aren't actually overlapping. So it is possible to specify outputs in a unique fashion e.g.
   ```yaml
   outputs:
     cohort1: output/input_2020_02_*.csv.gz
     cohort2: output/input_2020_03_*.csv.gz
     ...
   ```

   This is all a bit verbose and tiresome, but it is do-able.


2. Part of what makes this particularly verbose and tiresome is our very limited glob syntax. If we had e.g. brace expansion support we could do something like:
   ```yaml
   outputs:
     cohort: output/input_2020_{02,03,04,05}_*.csv.gz
   ```
   which might make it all a bit more manageable, and might be otherwise useful as well.

3. We might find that since [this change](https://github.com/opensafely-core/cohort-extractor/pull/774) even current cohortextractor is more reliable and this workaround isn't needed as much.

4. Longer term I'd like to move to having a single "[fetch data and generate measures](https://github.com/opensafely-core/databuilder/issues/42)" command and so this specific problem of having loads of intermediate outputs to extract just goes away.

**Comment by iaindillingham** [comment]
> Could whoever picks this ticket up go over each of those with all the others in mind, and attempt to summarize the work that needs doing? And then put the above in a reasonable order of priority / dependency? (And potentially identify gaps in the work that need tickets too).

**Summarize the work that needs doing.** I've renamed the issues and, where necessary, summarized them. (This often wasn't necessary!) I've moved them to the Regatta project for triage. Where they were already in the Regatta project, I've moved them back to triage, to maintain dependency order.

**Put the issues in reasonable priority/dependency order.** This is given in the checklist; the rationale is given in the comment.

**Identify gaps.** I found this hard. I'm not aware of any gaps, but I also haven't been immersed in job-runner.

> Then pass this ticket to me (Seb) and I will close it and prioritize the resulting tickets in our backlog / next queue.

Done.

**Comment by sebbacon** [comment]
Superseded by https://github.com/opensafely-core/job-runner/issues/406
