### ISSUE TITLE
Encode privacy levels via reserved directory names

### ISSUE THREAD

**Issue by evansd** [opensafely-core/job-runner#320]
I think that rather than specifying the privacy level of outputs via yaml keys like this:
```yaml
outputs:
  highly_sensitive:
    cohort: output/input.csv
  moderately_sensitive:
    analysis: outputs/data_properties.csv
```

We should just insist that highly sensitive files go in a special `high_privacy` (or whatever we want to call it) directory:
```yaml
outputs:
  - high_privacy/cohort.csv
  - outputs/data_properties.csv
```

I think this has several advantages:
 * It's syntactically less noisy.
 * It's simple to understand.
 * In combination with [#319](https://github.com/opensafely-core/job-runner/issues/319) it makes it obvious when an action is consuming high privacy files as _inputs_.
 * It significantly simplifies the mechanics of access control. In fact, it's quite feasible that all responsibility for maintaining a separate level 4 copy of the workspace could be taken out of job-runner and the "sync to level 4" process that TPP are using could be configured to not copy the `high_privacy` directory.

One potential downside is a loss of flexibility: you can't put high privacy files wherever you want to. But I don't think in practice this will be a big restriction, and you could even argue its a positive.

Another potential downside is a loss of explicitness. But I don't feel there's any loss of clarity to the reader, as long as we choose the right directory name. We could even add the directory to default template with a README in it (and a suitable gitignore) which explains exactly what the directory is for. And as for researchers inadvertently putting high privacy files in the wrong place, that happens under the current system anyway and I think the right solution here is #315.

**Comment by evansd** [comment]
> * how'd we guard against typos? `- high_prvacy/cohort.csv` could lead to confusing situations

I think #315 is the answer here. We can detect locally and in test when high privacy output inadvertently ends up in the wrong place. I think you're right that it's slightly easier to make this kind of mistake under this scheme than the existing one. But given that people have already got this wrong under the existing scheme I think we need #315 anyway, and then the difference goes away.

> * could/would/should we hard code the `high_privacy` folder into the databuilder to enforce its use in that case?

Yes, or at least, almost yes. I think the solution is to always require an explicit output name in the databuilder so nothing is hardcoded there. And then job-runner, which already has to have special behave for the `generate_cohort` command, can enforce that the output file is always going to the right place. Of course this would also be caught by #315 but it would be nicer to give the error immediately on loading the project.yaml rather than having to wait until you run it.

**Comment by benbc** [comment]
Closing in favour of [this](https://docs.google.com/document/d/17wYPHviw7Ce659Z_Gfr-7AjfAQFKodfRusSuNZNHxxk/edit) option in our pipeline.
