### ISSUE TITLE
Delete files that shouldn't be on level 4

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/job-runner#393]
There are a small number of files copied over from level 3 to level 4 that shouldn't be. This arises due to accidental misclassification of output sensitivity, detailed in #315.

The files in the below workspaces need to be deleted from level 4.

`the_effects_of_covid_19_on_doac_prescribing`
`output/filtered/input_2018*.feather`

- [x] Deleted from L3
- [x] Deleted from L4

`lockdown_and_vulnerable_groups`
`output/input_2020*.csv`

- [x] Deleted from L3
- [x] Deleted from L4

`highcostdrugs_v3`
`output/input_hcd.csv`

- [x] Deleted from L3
- [x] Deleted from L4

`highcostdrugs_adalimumab_master`
`output/input_hcd.csv`
`output/input_adalimumab.csv`

- [x] Deleted from L3
- [x] Deleted from L4

`carehomeprescribing`
`output/old/input*.csv`

- [x] Deleted from L3
- [x] Deleted from L4

For all of the above, the code is either fixed or we don't expect to run the code again

**Comment by bloodearnest** [comment]
You'll need to delete from /srv/medium_privacy first, or else they'll just reappear in level 4.

**Comment by iaindillingham** [comment]
I've deleted the above from `/srv/medium_privacy` and from L4.
