### ISSUE TITLE
Expose maintenance mode to job server

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/job-runner#398]
[This commit](https://github.com/opensafely-core/job-runner/commit/d6cd30adb63001090c5b895f9f8fc3f55a7ea67d) has the breadcrumbs to do it - we want to pass the result of `get_flag("mode")` up to the job server so we can handle it in the UI.

[context from slack](https://bennettoxford.slack.com/archives/C010SJ89SA3/p1652091636752329?thread_ts=1651836883.315899&cid=C010SJ89SA3) 

[update]

Per comments below, it seems sensible to do this via a new top-level key in the json we post about jobs, which means this issue would have to be deployed at the same time as a corresponding new jobserver feature https://github.com/opensafely-core/job-server/issues/1789

**Comment by evansd** [comment]
We don't yet have a communication channel between job-runner and job-server that isn't job-based. At the moment, job-runner polls job-server and gets `JobRequests` and then posts back `Jobs`, and that's the only point of contact.

We definitely do want something more general purpose here (we've already discussed wanted to push up load measurements and other general system stats) but we haven't yet designed it. It may be that now's the time to think about it, but just wanted to flag up that some new endpoint (however crude) needs designing here.

The current interface will provide some feedback to user about maintenance mode (along the lines of "your job has been paused while the database undergoes maintenance; it will be automatically run later once maintenance is complete") but obviously that will come _after_ you've submitted the job so it's not ideal.

**Comment by bloodearnest** [comment]
I suggested on slack that a quick fix version of this could be adding a header to job-runner's poll request to job-server that indicates the current mode. That would be trivial to implement in job-runner, and job-server can do with it what it will.

**Comment by ghickman** [comment]
I don't think we should modify the response payload of the jobs API to handle this, primarily from a code maintenance perspective.

job-server's API handler for this endpoint is one of the more complex parts of that code base.  It's already 157 lines long as it needs to handle the updates of data in such a way that we can send notifications about the content elsewhere (this is how we handle job finishing notifications, sentry errors, etc).

A short-term solution for adding a banner to job-server would be an env var, a context processor, and a block in the base HTML template.  It's simple to toggle and fits with how our other cross-site messaging (missing backends) already works.

We've wanted a meta channel for non-job communitcation for a while now and this seems like a good threshold to start building it.  A new endpoint would allow us to iterate with a much lower likelihood of disrupting job syncing and avoid working in an already complex area of the codebase.

**Comment by sebbacon** [comment]
> A new endpoint would allow us to iterate with a much lower likelihood of disrupting job syncing and avoid working in an already complex area of the codebase.

A new endpoint potentially makes sense, because it certainly _feels_ like a different domain that deserves a different REST verb. But I'd like to interrogate that a bit more.  

Setting aside the code complexity point, what are its concrete advantages? 

* Deploy changes to non-job metadata isolated from jobs
* Ability to set non-job metadata on a different schedule from job metadata

On the other side:

* If we moved jobs to their own subkey then it isolates all the complex job code in a simple code branch, anyway
* Do we _need_ different schedules?
* At some point, we are going to want to reference jobs by id in some metadata, somehow (e.g. linking an individual job to its memory consumption). Doing so in a single message avoids race conditions on interpreting data at the receiving end
* Writing and managing a separate sync process adds a different kind of complexity

Thoughts?

**Comment by ghickman** [comment]
>  If we moved jobs to their own subkey then it isolates all the complex job code in a simple code branch, anyway

I think this is downplaying the existing complexity and various issues we've already seen because of said complexity with that endpoint.  While we could pull job data down into a key we've now coupled metadata about the entire service to specific job updates.

> At some point, we are going to want to reference jobs by id in some metadata, somehow (e.g. linking an individual job to its memory consumption). Doing so in a single message avoids race conditions on interpreting data at the receiving end

I'm not sold on this point, it feels like an edge-case, particularly since we're talking about exposing a non-job-related set of data here.  Maybe I'm missing potential uses of it though, do we have any currently?

> Do we need different schedules?
> Writing and managing a separate sync process adds a different kind of complexity

I think this is slightly orthoganal to a different endpoint, there's no reason we couldn't make two posts on the same schedule.  Pushing the data up shouldn't be (famous last words) the hard part of this.

---

This feels like a coupling/separation of concerns problem to me.  I don't see why service-level metadata needs to be passed up via the same API endpoint as status updates.

**Comment by sebbacon** [comment]
>> At some point, we are going to want to reference jobs by id in some metadata, somehow (e.g. linking an individual job to its memory consumption). Doing so in a single message avoids race conditions on interpreting data at the receiving end
>
> I'm not sold on this point, it feels like an edge-case, particularly since we're talking about exposing a non-job-related set of data here. Maybe I'm missing potential uses of it though, do we have any currently?

I'm making the case for something like a _general_ `metadata` key-or-new-endpoint. Some of this endpoint will contain global information, and some will be job-specific, and other things we know not what. The specific motivating use-case I have in mind is reporting on per-job memory usage, which is getting more and more urgent.

_If_ we were to include job-specific metadata in a different data structure, delivered to its own schedule, then a race condition wouldn't be an odd edge-case, but fairly common, I think.

**Comment by ghickman** [comment]
That makes sense, what about a mixture of both?

Including job-specific metadata with the existing status updates is no different to what we're already doing there.  We might need more fields on the Job model but that's simple enough.  Then any non-job metadata comes up via a separate endpoint.

This would mean trivial changes to the existing endpoint while keeping general service metadata separate.

I think that avoids the race-condition situation?

**Comment by bloodearnest** [comment]
We've had this for a while now
