### ISSUE TITLE
Improve file-copy time in local run mode

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/job-runner#408]
In "local run" mode, we have to rely on `docker cp` to move files into the expected location for an action to run, because this is the only way to make it work in Windows (see https://github.com/opensafely-core/job-runner/issues/169 for discussion).

This is irritatingly slow when there are lots of files (e.g. when generating measures)

It is possible that `rysnc`ing a whole directory may be faster (although [tests show](https://github.com/opensafely-core/job-runner/issues/169#issuecomment-1034204925) this isn't the case on Linux + zfs, it may be true on Windows).  Or perhaps it'd be faster to zip-copy-unzip?

Brainstorm and investigate; if there's low-hanging fruit, implement.

On the other hand, it's worth timeboxing, as we hope a future measures implementation might not be so slow.

**Comment by bloodearnest** [comment]
We have moved to bind mounts for this now, and use python stdlib's `shutil.copyfile` for the copy
