### ISSUE TITLE
Generate hashes in requirements files

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/job-runner#421]
Spotted while I was reviewing a PR that changed dependencies in this repository.

We generate hashes in our current [repository template](https://github.com/opensafely-core/repo-template) and most/all of our other platform projects.

Maybe there's a technical reason why we can't. But maybe it's just been missed?

**Comment by ghickman** [comment]
Unfortunately, we need to support running on multiple operating systems (primarily for opensafely-cli now) and we've yet to find a way to both use hashes and do that.

We're tracking this in opensafely-core/repo-template#52 for lack of a better place.
