### ISSUE TITLE
Gracefully handle `docker inspect` timeout

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-runner#453]
We periodically see the docker service get stuck responding to `docker inspect` here:

https://github.com/opensafely-core/job-runner/blob/master/jobrunner/executors/local.py#L188

This command timesout after the default of 300s, and then fails the job with internal error.

This is a good proportion (maybe around 50%?) of "Internal Errors" that the user and tech-support see, and it shouldn't be. It also means the main run loop of job-server is blocked for 300s, which is also bad. 

This particular `inspect` call is something we do to every job on every loop, and failing with a timeout it is not fatal (unlike say failing to get outputs, or find the container).

I think we should:

1) set a much shorted timeout, say 30s 
2) If it times out, *log it*, but raise an error that will not result in a job failure with internal error, but rather, the job will be skipped this run of the loop, and retried on the next run (as per normal for non-fatal errors).

This should allow us to ride out when docker has a hitch without failing a bunch of jobs.

However, this could result in a docker hang up getting jobs stuck. But such a case seems fairly catastrophic anyway, and would presumably result in many other failures. We could potentially handle this (e.g. tracking the number of timeouts and hard erroring if they reach a threshold, or similar schemes), but I'd be tempted to try it first.

**Comment by evansd** [comment]
This sounds sensible.

I think it would be worth treating the `inspect` calls happening on every loop separately to the calls that happen when preparing or finalising a job. The former can have a short timeout and non-fatal error behaviour, but I'd be inclined to leave the latter as they are.

But +1 to just trying it and worrying about tracking failure counts later.
