### ISSUE TITLE
SPIKE Attempt to find the cause of the docker timeouts

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-runner#504]
We are seeing a lot of internal job errors caused by Docker timeouts. This is obviously causing an issue for our users, but also creating an increasing burden on tech support.

We should set aside **one day** to investigate these errors and attempt to discover the underlying cause.

[See Slack conversation](https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1667387590302949)

Related: We have a ticket to cover gracefully handling `docker inspect` timeouts: https://github.com/opensafely-core/job-runner/issues/453

**Comment by bloodearnest** [comment]
The incidents seem to be related to memory exhaustion: https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner/result/B89Kc8PbE2M?tab=metrics

**Comment by bloodearnest** [comment]
Im now fairly certain that the timeouts are cause be low free memory https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner/result/9pN3aQ9VPbe?omitMissingValues&tab=metrics
