### ISSUE TITLE
Finish and rollout local volume api in TPP

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-runner#522]
The copying of files in and out of jobs workspace is slow. Also, it currently blocking, which means that in blocks the loop for a long time. 

In #433 we implemented a volume_api abstraction as part of shore leave, and added a bind mount implementation that is much faster, but only works on linux. The reason why its faster is its just coping on the host, not via docker cp, which a) goes over the network and b) uses the docker api, which can fail under load.

This was implemented as a run time config - we're using one api or the other.

However, when coming to try roll it out in prod, we realise that we needed to handle both at the same time, as jobs that were started with the old api will need use the same api to finalise them.

To have a smooth rollout, we need to select the api to use per job, rather than at boot time. That will allow use to switch to the bind mount api and still correctly handle in-flight jobs. And vice versa for rolling back.

**Comment by evansd** [comment]
Can we introspect the container to work out which API to use for finalising? Then we don't need an extra flag on the job.

**Comment by bloodearnest** [comment]
Yes, but currently the volume api to use is hardcoded for every job.

We need to change the api to be `get_volume_api(job)`. The code would likely be sth like
```
if docker.volume_exists(volume_name(job)):
    return DockerVolumeAPI
elif path_for_bind_mount_volume(job).exist():
    return BindMountVolumeAPI
else:
    return config.LOCAL_VOLUME_API
```

**Comment by evansd** [comment]
Ah got you, it's an API change rather than extra state on the job. Sorry for the noise!
