### ISSUE TITLE
Add Honeycomb metrics to containers on the backend

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-runner#535]
@bloodearnest to add more details into this ticket

**Comment by bloodearnest** [comment]
We already collect metrics periodically in a separate thread, and write them to a sqllite db

In the same thread, we also send the tick traces that tell us the current state of play.

We need to join these up, and add any current metrics for a running job to the tick trace spans.


Caveat: we currently use the `docker stats` api to get metrics. If possible, it would be nice to avoid using this, as it's not cheap. There are ways to get this information without hitting the docker api

**Comment by madwort** [comment]
can we add "create links from job server to the new metrics" to this ticket?

**Comment by bloodearnest** [comment]
Done in https://github.com/opensafely-core/job-server/pull/2530
