### ISSUE TITLE
Revisit docker timeout retry handling in job-runner

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-runner#546]
When docker server is timing out, its usually for a good while, and the current retry count then error approach is not avoiding the INTERNAL_ERRORS we'd hoped to with this change.

Much discussion in this thread https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1671702901142859

Ideally, we don't want to fail the job at all, but keep it waiting until docker recovers. But without an INTERNAL_ERROR, we don't have any alerting that its happening.

One options is to remove the retry count/errorring, and instead ensure the timeout is tracked in the tick traces we send to honeycomb. Then we can add an alert like "where count(tick spans with attribute docker_timeout=True) > threshold"

**Comment by evansd** [comment]
That sounds ideal, if it's doable without doing too much violence to the tracing code.
