### ISSUE TITLE
User cancelled jobs do not preserve logs

### ISSUE THREAD

**Issue by evansd** [opensafely-core/job-runner#562]
Since this PR we now preserve logs for jobs which will kill from the command line:

 * #514

But we don't do so for jobs cancelled by the user:
https://github.com/opensafely-core/job-runner/blob/e659124590791b40622368adc62787374aa3a11f/jobrunner/run.py#L194-L200

This would need similar logic to the above PR where we persist the logs to the long-term log archive, but don't touch anything in the workspace.

**Comment by bloodearnest** [comment]
https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1674750806804359

**Comment by madwort** [comment]
hopefully fixed by https://github.com/opensafely-core/job-runner/pull/601 , awaiting review

**Comment by madwort** [comment]
just pushed a rework of the logic handling the job/executor states to support cancelled jobs, with associated state diagram here: https://github.com/opensafely-core/job-runner/pull/601/commits/6cb81bae5884c4e4ca1cf6b146f55eb643ee2d68

there's still (what should be) a straightforward question of where to put the log files for cancelled jobs, but I now think I'm on top of the executor engine questions.

**Comment by madwort** [comment]
#601 now merged, although I'm pretty confident in the tests, would be good to see a cancelled job in production to verify that everything is as we expect

**Comment by madwort** [comment]
also @bloodearnest to file a PR with another diagram for the README

**Comment by madwort** [comment]
Dave said it works!!! https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1689853610728929
