### ISSUE TITLE
Run job-runner integration tests with BindMountVolumeAPI

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-runner#590]
Currently, the integration tests run local_run for cohortextractor and databuilder.

But they only run with the default DockerVolumeAPI, not with the BindMountVolumeAPI. We should run them with both APIs.

This likely would have help catch the permissions errors around deleting files with BindMountVolumeAPI that we hit in prod.

**Comment by lucyb** [comment]
@bloodearnest to point to the fixture that will help with this.

**Comment by bloodearnest** [comment]
https://github.com/opensafely-core/job-runner/blob/master/tests/test_local_executor.py#L22

**Comment by madwort** [comment]
useful things: #596 #597 #598

**Comment by madwort** [comment]
fixed by https://github.com/opensafely-core/job-runner/pull/591
