### ISSUE TITLE
Add honeycomb alert on unexpected job errors

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-runner#632]
Try alerts from honeycomb rather than relying on (currently broken) custom code in job-server

**Comment by bloodearnest** [comment]
Jobs that INTERNAL_ERROR: https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner/triggers/32TyFDooh2p


Unexpected database errors: https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner/triggers/xiDh41qeftk


OOM killed jobs: https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner/triggers/43bcJY7HNBT




Once we're happy these are working, I think we can probably just remove this function from job-server https://github.com/opensafely-core/job-server/blob/main/jobserver/api/jobs.py#L203
