### ISSUE TITLE
Jobs are failing with an internal error when they should be returning an out of memory error message

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-runner#636]
When a job runs out of memory it should return back an error to the user. However, for some reason they're currently failing with an internal error, which makes it look like there was a problem with the system (thread [one](https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1692705601846719), [two](https://bennettoxford.slack.com/archives/C0270Q313H7/p1692714149137809)). This is giving us extraneous alerts and giving users the wrong information so they retry jobs that will never work.

Note: we don't know how often this is happening and whether it's all jobs that run out of memory or just some of them (we currently think it's all of them)

**Comment by bloodearnest** [comment]
Fixed with #643
