### ISSUE TITLE
Don't notify tech support for stale codelists

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-runner#681]
We've had an INTERNAL_ERROR notification to the `tech-support-channel` about a [job request with a stale codelist error](https://jobs.opensafely.org/investigating-the-effectiveness-of-the-covid-19-vaccination-programme-in-the-uk/comparative-booster-spring2023/21229/).

This is a known error case with a documented process for users to follow so we shouldn't be notifying tech support.  Could we not be handling the error case in job-server's API so we think it's unknown?

The output on job-server looks correct, but we should check that it's using our usual `__error__` mechanism.

**Comment by bloodearnest** [comment]
Another incidence of this: https://jobs.opensafely.org/investigating-the-effectiveness-of-the-covid-19-vaccination-programme-in-the-uk/comparative-booster-spring2023/21516/

**Comment by bloodearnest** [comment]
Here is the problem:

https://github.com/opensafely-core/job-runner/blob/main/jobrunner/create_or_update_jobs.py#L340

JobRequestError is meant to indicate a sync protocol error, so is an INTERNAL_ERROR.  The codelist check is *not* a protocol error, its a user error, so it should be handled differently.

We probably need a new StaleCodelistError

**Comment by bloodearnest** [comment]
Fixed in https://github.com/opensafely-core/job-runner/pull/700
