### ISSUE TITLE
Check state transitions/telemetry is correctly handled when engaging db maintenance mode

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/job-runner#683]
We should see the job trace go `EXECUTING` -> `WAITING_FOR_MAINTENANCE` -> `EXECUTING`, but we don't seem to. Its possible we're not recording the transition properly in the *job* trace. It does seem to be correct in the tick traces.

**Comment by madwort** [comment]
you mean `WAITING_DB_MAINTENANCE`, right?

**Comment by madwort** [comment]
example data, tick traces https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner/result/F82iVKNytHp?omitMissingValues&useStackedGraphs

**Comment by madwort** [comment]
on further investigation, there does not appear to be any issue
