### ISSUE TITLE
Remove killed by admin status

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/job-runner#684]
The "killed by admin" [state](https://github.com/opensafely-core/job-runner/blob/c44f6f8a5aeb2249f8c595dc6b20e6032326d34a/jobrunner/models.py#L74) and [status code](https://github.com/opensafely-core/job-runner/blob/c44f6f8a5aeb2249f8c595dc6b20e6032326d34a/jobrunner/models.py#L89) hasn't been implemented yet, but its existence implies that it works and has caused some confusion. The code should be removed until we are ready to implement the functionality.

**Comment by lucyb** [comment]
Edit: this could be a code comment instead.

**Comment by madwort** [comment]
I think this state/status_code is used correctly when jobs are [killed via cli](https://github.com/opensafely-core/job-runner/blob/c44f6f8a5aeb2249f8c595dc6b20e6032326d34a/jobrunner/cli/kill_job.py#L23), but not when killed by an admin from the job-server interface.
