### ISSUE TITLE
Possibly unused branch in create_or_update_jobs

### ISSUE THREAD

**Issue by madwort** [opensafely-core/job-runner#696]
Whilst thinking about a [different issue](https://github.com/opensafely-core/job-runner/issues/681), I was looking at this code:

https://github.com/opensafely-core/job-runner/blob/main/jobrunner/create_or_update_jobs.py#L331-L337

and although it is executed directly by the tests, I don't think it's possible to hit this branch from the code here https://github.com/opensafely-core/job-runner/blob/main/jobrunner/create_or_update_jobs.py#L53-L68

and I'm not able to find anywhere else that could send us to this branch. I've also just had a look in honeycomb & I'm not able to find an example job/job_request that has output this specific error. Can we delete this code? Should we reimplement in a way that will get called?

**Comment by evansd** [comment]
I _think_ it used to be possible to hit this branch by requesting `run_all` when all actions had already successfully run. But something may well have changed so that that's longer possible.

**Comment by madwort** [comment]
this was actually fine, I'd misread something
