### ISSUE TITLE
Actions running out of order when a job is rerun

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/job-runner#703]
https://bennettoxford.slack.com/archives/C33TWNQ1J/p1705572676801459

The following was reported to support:

> I ran some jobs, let's say A -> B -> C. But C finished before B, and B finished before A. I've checked the dependencies are as expected and I'm fairly sure nothing is wrong there.
>
> The state of the repo before submitted the jobs was A(success), B(success), C(fail). So I fixed what was causing C to fail and reran. It looks like job runner started running B and C straight away because their respective antecedents had already run successfully, even though I requested a rerun in the same job request.
>
> I remember a conversation (long ago!) that job runner would do the right thing in this scenario, but it looks like that isn't happening any more?
>
> This is the job request: https://jobs.opensafely.org/investigating-the-effectiveness-of-the-covid-19-vaccination-programme-in-the-uk/comparative-booster-spring2023/21765/
>
> It's a bit more complicated than A,B,C. But if you look at dependencies and completion times for `extract` -> .... -> `match_cv_B` -> `match_cv_B_report` you should see what I mean.
> …
> Actually it looks like the match actions ran correctly in sequence. But they started and finished before `extract` had finished (it's still running)

**Comment by StevenMaude** [comment]
![A list of actions in job-server for the job with the reported issue.](https://github.com/opensafely-core/job-runner/assets/3818079/c2848d4e-2658-4648-9daa-0f539764beed)

One example of the incorrect ordering for the [project.yaml](https://github.com/opensafely/comparative-booster-spring2023/blob/530c45a707d57ca1fbec07da691f3ba04ed2e6b9/project.yaml) I think is:

`match_cv_A` needs `data_selection_cv`
`data_selection_cv` needs `data_process`
`data_process` needs `extract`

`extract` is running; `data_process` is pending presumably waiting for `extract`, yet `match_cv_A` is running.

**Comment by madwort** [comment]
`match_cv_A` requires `data_selection_cv`, which is not in the specified list of actions - so it doesn't matter whether `match_cv_A` waits for `extract` to finish, it would always use the stale data?

**Comment by evansd** [comment]
I think this is related to the behaviour discussed below whereby there's no mechanism that automatically marks the results of downstream actions as stale when an upstream action is re-run:
 * https://github.com/opensafely-core/job-runner/issues/196
