### ISSUE TITLE
job-runner-tpp-token will expire on 2024-10-02

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-runner#739]
I'm afraid I don't (currently) have access to TPP, so I can't renew job-runner-tpp-token myself. It's owned by @opensafely-readonly. There's more information [in Slack](https://bennettoxford.slack.com/files/USLACKBOT/F07NT3CEDBP/_github__your_personal_access_token__classic__is_about_to_expire).

**Comment by evansd** [comment]
All done, as per instructions here:
https://bennett.wiki/tech-group/playbooks/team-rap/#job-runner
