### ISSUE TITLE
Add debug logging

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/job-runner#87]
The v2 runner doesn't currently explain much of what it does when it's doing it, for instance, what caused it to fail to make a Job.

I think we could do with general flow logs, particularly for any decision points, and more verbose logs set to the `DEBUG` level.

**Comment by evansd** [comment]
Yes, very much agree. At the moment I'm logging everything at INFO, and we really need to divide up into `DEBUG`, `INFO` and `WARN` and then add a lot more debugging info.

**Comment by evansd** [comment]
We should add a `--verbose` flag (or the equivalent) to the `opensafely run` command which enables `DEBUG` level log output.

We should also include in the debug log the exact `docker run` invocation that gets used, as the old system did.

**Comment by bloodearnest** [comment]
Added in 492168eb
